<?php
namespace DigitalProducts;

use DigitalProducts\Core\Audit;
use DigitalProducts\Core\Csrf;
use DigitalProducts\Core\Rbac;
use DigitalProducts\Core\Settings;
use DigitalProducts\Services\EntitlementService;
use DigitalProducts\Services\VersionService;
use WHMCS\Database\Capsule;

class Admin
{
    protected $vars; protected $core; protected $moduleLink; protected $action; protected $error = ''; protected $success = '';
    public function __construct(array $vars) { $this->vars = $vars; $this->core = new Core(); $this->moduleLink = $vars['modulelink']; $this->action = preg_replace('/[^a-z-]/', '', (string) ($_GET['action'] ?? 'dashboard')); }

    public function render()
    {
        $authorized = true;
        try { Rbac::authorize(Rbac::PRODUCTS_VIEW); $this->handlePost(); } catch (\Throwable $e) { $this->error = $e->getMessage(); $authorized = false; }
        ob_start(); echo '<div class="digitalproducts-admin">';
        if (!$authorized) { echo '<div class="alert alert-danger">' . $this->e($this->error) . '</div></div>'; return ob_get_clean(); }
        $this->nav();
        if ($this->error) echo '<div class="alert alert-danger">' . $this->e($this->error) . '</div>';
        if ($this->success) echo '<div class="alert alert-success">' . $this->e($this->success) . '</div>';
        try { switch ($this->action) { case 'products': $this->products(); break; case 'product-edit': $this->productEdit(); break; case 'upload': $this->upload(); break; case 'versions': $this->versions(); break; case 'entitlements': $this->entitlements(); break; case 'licenses': $this->licenses(); break; case 'downloads': $this->downloads(); break; case 'api': $this->api(); break; case 'settings': $this->settings(); break; default: $this->dashboard(); } } catch (\Throwable $e) { echo '<div class="alert alert-danger">Unable to load this section. Check the activity log.</div>'; if (function_exists('logActivity')) logActivity('DigitalProducts admin error: ' . $e->getMessage()); }
        echo '</div>'; return ob_get_clean();
    }

    protected function handlePost()
    {
        if (($_SERVER['REQUEST_METHOD'] ?? 'GET') !== 'POST') return;
        Csrf::verify();
        $action = (string) ($_POST['dp_action'] ?? '');
        if ($action === 'create_product') { Rbac::authorize(Rbac::PRODUCTS_MANAGE); $id = $this->core->createDigitalProduct((int) $_POST['whmcs_product_id']); Audit::record('product.created', 'product:' . $id); $this->success = 'Product linked. Set its status to Active before publishing a release.'; return; }
        if ($action === 'save_product') { Rbac::authorize(Rbac::PRODUCTS_MANAGE); $id = (int) $_POST['product_id']; $this->core->updateDigitalProduct($id, ['name' => trim($_POST['name'] ?? ''), 'product_name' => trim($_POST['name'] ?? ''), 'description' => $_POST['description'] ?? '', 'short_description' => $_POST['short_description'] ?? '', 'status' => in_array($_POST['status'] ?? '', ['draft', 'active', 'inactive', 'retired'], true) ? $_POST['status'] : 'draft', 'product_type' => $_POST['product_type'] ?? 'software', 'download_limit' => max(0, (int) ($_POST['download_limit'] ?? 0)), 'download_expiry_hours' => max(0, (int) ($_POST['download_expiry_hours'] ?? 48)), 'link_expiry_hours' => max(0, (int) ($_POST['download_expiry_hours'] ?? 48)), 'access_mode' => in_array($_POST['access_mode'] ?? '', ['current_version', 'purchase_version'], true) ? $_POST['access_mode'] : 'current_version', 'license_enabled' => !empty($_POST['license_enabled'])]); Audit::record('product.updated', 'product:' . $id); $this->success = 'Product updated.'; return; }
        if ($action === 'upload_version') { Rbac::authorize(Rbac::FILES_UPLOAD); $version = (new VersionService())->upload((int) $_POST['product_id'], $_POST['version'] ?? '', $_FILES['file'] ?? [], ['changelog' => $_POST['changelog'] ?? '', 'release_notes' => $_POST['release_notes'] ?? '', 'min_php' => $_POST['min_php'] ?? null, 'max_php' => $_POST['max_php'] ?? null, 'min_whmcs' => $_POST['min_whmcs'] ?? null, 'max_whmcs' => $_POST['max_whmcs'] ?? null, 'publish' => !empty($_POST['publish']), 'set_current' => !empty($_POST['set_current'])]); $this->success = 'Version ' . $version->version . ' uploaded and verified.'; return; }
        if ($action === 'publish_version') { Rbac::authorize(Rbac::VERSIONS_MANAGE); (new VersionService())->publish((int) $_POST['version_id']); $this->success = 'Version published.'; return; }
        if ($action === 'set_current') { Rbac::authorize(Rbac::VERSIONS_MANAGE); (new VersionService())->setCurrent((int) $_POST['product_id'], (int) $_POST['version_id']); $this->success = 'Current version changed.'; return; }
        if ($action === 'retire_version') { Rbac::authorize(Rbac::FILES_DELETE); (new VersionService())->retire((int) $_POST['version_id']); $this->success = 'Version retired. The physical file was preserved.'; return; }
        if ($action === 'entitlement') { Rbac::authorize(Rbac::ENTITLEMENTS_MANAGE); $service = new EntitlementService(); $id = (int) $_POST['entitlement_id']; $op = $_POST['operation'] ?? ''; if ($op === 'reset') { $service->resetCounter($id); Audit::record('entitlement.counter_reset', 'entitlement:' . $id); } elseif ($op === 'revoke') { Capsule::table('mod_digitalproducts_entitlements')->where('id', $id)->update(['status' => 'revoked', 'revoked_reason' => 'admin_revoked', 'updated_at' => date('Y-m-d H:i:s')]); Audit::record('entitlement.revoked', 'entitlement:' . $id); } elseif ($op === 'restore') { Capsule::table('mod_digitalproducts_entitlements')->where('id', $id)->update(['status' => 'active', 'revoked_reason' => null, 'updated_at' => date('Y-m-d H:i:s')]); Audit::record('entitlement.restored', 'entitlement:' . $id); } $this->success = 'Entitlement updated.'; return; }
        if ($action === 'license_status') { Rbac::authorize(Rbac::LICENSES_MANAGE); (new License())->updateLicenseStatus((int) $_POST['license_id'], $_POST['status'] ?? 'suspended'); Audit::record('license.status_changed', 'license:' . (int) $_POST['license_id']); $this->success = 'License updated.'; return; }
        if ($action === 'issue_api_token') { Rbac::authorize(Rbac::SETTINGS_MANAGE); $issued = (new \DigitalProducts\Services\ApiTokenService())->issue((int) $_POST['client_id'], $_POST['token_name'] ?? 'CloudHost247 integration', ['my-downloads', 'download-token', 'my-licenses']); $this->success = 'Token created. Copy it now; it will not be shown again: ' . $issued['token']; return; }
        if ($action === 'revoke_api_token') { Rbac::authorize(Rbac::SETTINGS_MANAGE); (new \DigitalProducts\Services\ApiTokenService())->revoke((int) $_POST['token_id']); $this->success = 'API token revoked.'; return; }
        if ($action === 'save_settings') { Rbac::authorize(Rbac::SETTINGS_MANAGE); Settings::validate($_POST); $path = trim((string) ($_POST['storage_path'] ?? '')); if ($path !== '') (new \DigitalProducts\Storage\LocalPrivateStorage($path)); Settings::setMany(['download_limit' => max(0, (int) $_POST['download_limit']), 'link_expiry_hours' => max(0, (int) $_POST['link_expiry_hours']), 'access_mode' => $_POST['access_mode'], 'max_upload_size' => max(1, (int) $_POST['max_upload_size']), 'allowed_extensions' => strtolower(trim($_POST['allowed_extensions'])), 'storage_path' => $path, 'api_rate_limit' => max(1, (int) $_POST['api_rate_limit'])]); Audit::record('settings.changed', 'settings'); $this->success = 'Settings saved.'; }
    }

    protected function nav() { $items = ['dashboard' => 'Dashboard', 'products' => 'Products', 'upload' => 'Upload version', 'versions' => 'Versions', 'entitlements' => 'Entitlements', 'licenses' => 'Licenses', 'downloads' => 'Downloads', 'api' => 'API tokens', 'settings' => 'Settings']; echo '<ul class="nav nav-pills" style="margin-bottom:20px">'; foreach ($items as $key => $label) echo '<li class="' . ($this->action === $key ? 'active' : '') . '"><a href="' . $this->url($key) . '">' . $this->e($label) . '</a></li>'; echo '</ul>'; }
    protected function dashboard() { $s = $this->core->getDashboardStats(); echo '<div class="row">'; foreach (['products' => 'Products', 'active_products' => 'Active products', 'versions' => 'Versions', 'purchases' => 'Entitlements', 'licenses' => 'Active licenses', 'today_downloads' => 'Downloads today', 'month_downloads' => 'Downloads this month', 'failed_downloads' => 'Denied downloads'] as $key => $label) echo '<div class="col-sm-3"><div class="dp-stat-card"><div class="number">' . (int) $s[$key] . '</div><div class="text-muted">' . $this->e($label) . '</div></div></div>'; echo '</div><div class="panel panel-default"><div class="panel-heading"><strong>CloudHost247 delivery controls</strong></div><div class="panel-body">Files are stored privately, tokens are hashed and expiring, and access is rechecked against WHMCS on every download.</div></div>'; }
    protected function products() { $products = $this->core->getAllProducts(null); echo '<div class="panel panel-default"><div class="panel-heading clearfix"><strong>Digital Products</strong><a class="btn btn-primary btn-sm pull-right" href="' . $this->url('product-edit') . '">Link WHMCS product</a></div><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Product</th><th>WHMCS product</th><th>Status</th><th>Current</th><th>Actions</th></tr></thead><tbody>'; foreach ($products as $p) { $v = $p->current_version_id ? $this->core->getFileById($p->current_version_id) : null; echo '<tr><td><strong>' . $this->e($p->name ?: $p->product_name) . '</strong><br><small class="text-muted">' . $this->e($p->product_type) . '</small></td><td>' . $this->e($p->whmcs_product_name ?: $p->whmcs_product_id) . '</td><td>' . $this->badge($p->status) . '</td><td>' . $this->e($v ? $v->version : 'Not published') . '</td><td><a class="btn btn-default btn-xs" href="' . $this->url('product-edit', ['id' => $p->id]) . '">Edit</a> <a class="btn btn-default btn-xs" href="' . $this->url('upload', ['product_id' => $p->id]) . '">Upload</a></td></tr>'; } if (!$products) echo '<tr><td colspan="5" class="text-muted">No products linked.</td></tr>'; echo '</tbody></table></div></div>'; }
    protected function productEdit() { $id = (int) ($_GET['id'] ?? 0); if (!$id) { $this->linkForm(); return; } $p = Capsule::table('mod_digitalproducts_products')->where('id', $id)->first(); if (!$p) { echo '<div class="alert alert-danger">Product not found.</div>'; return; } echo '<div class="panel panel-default"><div class="panel-heading"><strong>Edit product: ' . $this->e($p->name ?: $p->product_name) . '</strong></div><div class="panel-body">'; $this->formStart('product-edit'); echo '<input type="hidden" name="dp_action" value="save_product"><input type="hidden" name="product_id" value="' . $id . '">' . $this->field('Name', '<input class="form-control" name="name" required value="' . $this->e($p->name ?: $p->product_name) . '">') . $this->field('Short description', '<input class="form-control" name="short_description" value="' . $this->e($p->short_description) . '">') . $this->field('Description', '<textarea class="form-control" name="description" rows="4">' . $this->e($p->description) . '</textarea>') . $this->field('Type', '<select class="form-control" name="product_type">' . $this->options(['module', 'plugin', 'theme', 'script', 'software', 'template', 'api', 'document', 'media', 'other'], $p->product_type) . '</select>') . $this->field('Status', '<select class="form-control" name="status">' . $this->options(['draft', 'active', 'inactive', 'retired'], $p->status) . '</select>') . $this->field('Access mode', '<select class="form-control" name="access_mode">' . $this->options(['current_version', 'purchase_version'], $p->access_mode) . '</select>') . $this->field('Download limit (0 = unlimited)', '<input class="form-control" type="number" min="0" name="download_limit" value="' . (int) $p->download_limit . '">') . $this->field('Link expiry hours (0 = never)', '<input class="form-control" type="number" min="0" name="download_expiry_hours" value="' . (int) $p->download_expiry_hours . '">') . $this->field('License keys', '<label><input type="checkbox" name="license_enabled" value="1"' . ($p->license_enabled ? ' checked' : '') . '> Generate licenses</label>') . '<button class="btn btn-primary" type="submit">Save product</button></form></div></div>'; }
    protected function linkForm() { echo '<div class="panel panel-info"><div class="panel-heading"><strong>Link a WHMCS product</strong></div><div class="panel-body">'; $this->formStart('product-edit'); echo '<input type="hidden" name="dp_action" value="create_product"><select class="form-control" name="whmcs_product_id" required><option value="">Select...</option>'; foreach ($this->core->getUnlinkedWhmcsProducts() as $p) echo '<option value="' . (int) $p->id . '">' . $this->e($p->name) . ' (' . $this->e($p->type) . ')</option>'; echo '</select><br><button class="btn btn-primary">Link product</button></form></div></div>'; }
    protected function upload() { $products = $this->core->getAllProducts(null); echo '<div class="panel panel-default"><div class="panel-heading"><strong>Upload a verified release</strong></div><div class="panel-body">'; $this->formStart('upload', true); echo '<input type="hidden" name="dp_action" value="upload_version">' . $this->field('Product', '<select class="form-control" name="product_id" required><option value="">Select...</option>' . $this->productOptions($products, (int) ($_GET['product_id'] ?? 0)) . '</select>') . $this->field('Version', '<input class="form-control" name="version" required placeholder="2.4.1">') . $this->field('File', '<input class="form-control" type="file" name="file" required>') . $this->field('Release notes', '<textarea class="form-control" name="release_notes"></textarea>') . $this->field('Changelog', '<textarea class="form-control" name="changelog"></textarea>') . $this->field('Compatibility', '<div class="row"><div class="col-sm-3"><input class="form-control" name="min_php" placeholder="Min PHP"></div><div class="col-sm-3"><input class="form-control" name="max_php" placeholder="Max PHP"></div><div class="col-sm-3"><input class="form-control" name="min_whmcs" placeholder="Min WHMCS"></div><div class="col-sm-3"><input class="form-control" name="max_whmcs" placeholder="Max WHMCS"></div></div>') . '<label><input type="checkbox" name="publish" value="1"> Publish version</label> <label><input type="checkbox" name="set_current" value="1"> Set current</label><br><button class="btn btn-primary" type="submit">Upload and verify</button></form></div></div>'; }
    protected function versions() { $products = $this->core->getAllProducts(null); foreach ($products as $p) { echo '<div class="panel panel-default"><div class="panel-heading"><strong>' . $this->e($p->name ?: $p->product_name) . '</strong></div><div class="table-responsive"><table class="table"><tr><th>Version</th><th>Checksum</th><th>Status</th><th>Action</th></tr>'; foreach ($this->core->getProductFiles($p->id) as $v) { echo '<tr><td>' . $this->e($v->version) . '</td><td><code>' . $this->e(substr($v->checksum_sha256, 0, 16)) . '…</code></td><td>' . $this->badge($v->status) . '</td><td>'; if ($v->status === 'draft') { $this->formStart('versions'); echo '<input type="hidden" name="dp_action" value="publish_version"><input type="hidden" name="version_id" value="' . (int) $v->id . '"><button class="btn btn-primary btn-xs">Publish</button></form> '; } if ($v->status === 'active' && $p->current_version_id != $v->id) { $this->formStart('versions'); echo '<input type="hidden" name="dp_action" value="set_current"><input type="hidden" name="product_id" value="' . (int) $p->id . '"><input type="hidden" name="version_id" value="' . (int) $v->id . '"><button class="btn btn-success btn-xs">Set current</button></form> '; } if ($v->status !== 'retired') { $this->formStart('versions'); echo '<input type="hidden" name="dp_action" value="retire_version"><input type="hidden" name="version_id" value="' . (int) $v->id . '"><button class="btn btn-warning btn-xs">Retire</button></form>'; } echo '</td></tr>'; } echo '</table></div></div>'; } }
    protected function entitlements() { $rows = Capsule::table('mod_digitalproducts_entitlements as e')->leftJoin('mod_digitalproducts_products as p', 'p.id', '=', 'e.product_id')->leftJoin('tblclients as c', 'c.id', '=', 'e.client_id')->select('e.*', 'p.name', 'p.product_name', 'c.firstname', 'c.lastname', 'c.email')->orderBy('e.created_at', 'desc')->limit(100)->get(); echo '<div class="panel panel-default"><div class="panel-heading"><strong>Entitlements</strong></div><div class="table-responsive"><table class="table"><tr><th>Customer</th><th>Product</th><th>Status</th><th>Downloads</th><th>Actions</th></tr>'; foreach ($rows as $r) { echo '<tr><td>' . $this->e(trim($r->firstname . ' ' . $r->lastname)) . '<br><small>' . $this->e($r->email) . '</small></td><td>' . $this->e($r->name ?: $r->product_name) . '</td><td>' . $this->badge($r->status) . '</td><td>' . (int) $r->downloads_used . ' / ' . ((int) $r->download_limit ?: '∞') . '</td><td>'; foreach (['reset' => 'Reset', 'restore' => 'Restore', 'revoke' => 'Revoke'] as $op => $label) { $this->formStart('entitlements'); echo '<input type="hidden" name="dp_action" value="entitlement"><input type="hidden" name="entitlement_id" value="' . (int) $r->id . '"><input type="hidden" name="operation" value="' . $op . '"><button class="btn btn-default btn-xs">' . $label . '</button></form> '; } echo '</td></tr>'; } echo '</table></div></div>'; }
    protected function licenses() { $rows = Capsule::table('mod_digitalproducts_licenses as l')->leftJoin('mod_digitalproducts_products as p', 'p.id', '=', 'l.product_id')->leftJoin('tblclients as c', 'c.id', '=', 'l.client_id')->select('l.*', 'p.name', 'p.product_name', 'c.firstname', 'c.lastname', 'c.email')->orderBy('l.created_at', 'desc')->limit(100)->get(); echo '<div class="panel panel-default"><div class="panel-heading"><strong>Licenses</strong></div><div class="table-responsive"><table class="table"><tr><th>Prefix</th><th>Product</th><th>Customer</th><th>Status</th><th>Action</th></tr>'; foreach ($rows as $r) { echo '<tr><td><code>' . $this->e($r->license_prefix ?: substr((string) $r->license_key, 0, 10)) . '…</code></td><td>' . $this->e($r->name ?: $r->product_name) . '</td><td>' . $this->e(trim($r->firstname . ' ' . $r->lastname)) . '</td><td>' . $this->badge($r->status) . '</td><td>'; $new = $r->status === 'active' ? 'suspended' : 'active'; $this->formStart('licenses'); echo '<input type="hidden" name="dp_action" value="license_status"><input type="hidden" name="license_id" value="' . (int) $r->id . '"><input type="hidden" name="status" value="' . $new . '"><button class="btn btn-default btn-xs">' . ucfirst($new) . '</button></form></td></tr>'; } echo '</table></div></div>'; }
    protected function downloads() { $logs = $this->core->getDownloadLogs((int) ($_GET['page'] ?? 1), 50, []); echo '<div class="panel panel-default"><div class="panel-heading"><strong>Download activity</strong></div><div class="table-responsive"><table class="table"><tr><th>Time</th><th>Customer</th><th>Product</th><th>Version</th><th>Status</th><th>Failure</th></tr>'; foreach ($logs['data'] as $r) echo '<tr><td>' . $this->e($r->created_at) . '</td><td>' . $this->e(trim($r->firstname . ' ' . $r->lastname)) . '</td><td>' . $this->e($r->name ?: $r->product_name) . '</td><td>' . $this->e($r->version) . '</td><td>' . $this->badge($r->status) . '</td><td>' . $this->e($r->failure_reason) . '</td></tr>'; echo '</table></div></div>'; }
    protected function api() { $rows = Capsule::table('mod_digitalproducts_api_tokens')->select('id', 'client_id', 'token_name', 'last_used_at', 'expires_at', 'created_at')->orderBy('created_at', 'desc')->limit(100)->get(); echo '<div class="panel panel-default"><div class="panel-heading"><strong>API tokens</strong></div><div class="panel-body">'; $this->formStart('api'); echo '<input type="hidden" name="dp_action" value="issue_api_token">' . $this->field('Client ID', '<input class="form-control" type="number" min="1" name="client_id" required>') . $this->field('Token name', '<input class="form-control" name="token_name" required>') . '<button class="btn btn-primary">Create token</button></form></div><div class="table-responsive"><table class="table"><tr><th>Client</th><th>Name</th><th>Last used</th><th>Action</th></tr>'; foreach ($rows as $r) { echo '<tr><td>' . (int) $r->client_id . '</td><td>' . $this->e($r->token_name) . '</td><td>' . $this->e($r->last_used_at ?: 'Never') . '</td><td>'; $this->formStart('api'); echo '<input type="hidden" name="dp_action" value="revoke_api_token"><input type="hidden" name="token_id" value="' . (int) $r->id . '"><button class="btn btn-danger btn-xs">Revoke</button></form></td></tr>'; } echo '</table></div></div>'; }
    protected function settings() { $s = $this->core->getSettings(); echo '<div class="panel panel-default"><div class="panel-heading"><strong>Settings</strong></div><div class="panel-body">'; $this->formStart('settings'); echo '<input type="hidden" name="dp_action" value="save_settings">' . $this->field('Default download limit', '<input class="form-control" type="number" min="0" name="download_limit" value="' . (int) ($s['download_limit'] ?? 5) . '">') . $this->field('Token expiry hours', '<input class="form-control" type="number" min="0" name="link_expiry_hours" value="' . (int) ($s['link_expiry_hours'] ?? 48) . '">') . $this->field('Default access mode', '<select class="form-control" name="access_mode">' . $this->options(['current_version', 'purchase_version'], $s['access_mode'] ?? 'current_version') . '</select>') . $this->field('Max upload bytes', '<input class="form-control" type="number" min="1" name="max_upload_size" value="' . (int) ($s['max_upload_size'] ?? 524288000) . '">') . $this->field('Allowed extensions', '<input class="form-control" name="allowed_extensions" value="' . $this->e($s['allowed_extensions'] ?? '') . '">') . $this->field('Private storage path', '<input class="form-control" name="storage_path" value="' . $this->e($s['storage_path'] ?? '') . '"><small class="help-block">Must be outside ROOTDIR.</small>') . $this->field('API rate limit', '<input class="form-control" type="number" min="1" name="api_rate_limit" value="' . (int) ($s['api_rate_limit'] ?? 60) . '">') . '<button class="btn btn-primary">Save settings</button></form></div></div>'; }
    protected function productOptions($products, $selected) { $out = ''; foreach ($products as $p) { if ($p->status === 'retired') continue; $out .= '<option value="' . (int) $p->id . '"' . ($selected === (int) $p->id ? ' selected' : '') . '>' . $this->e($p->name ?: $p->product_name) . '</option>'; } return $out; }
    protected function formStart($action, $upload = false) { echo '<form method="post" action="' . $this->url($action) . '"' . ($upload ? ' enctype="multipart/form-data"' : '') . '>'; echo Csrf::field(); }
    protected function field($label, $input) { return '<div class="form-group"><label class="control-label">' . $this->e($label) . '</label>' . $input . '</div>'; }
    protected function options(array $values, $selected) { $out = ''; foreach ($values as $v) $out .= '<option value="' . $this->e($v) . '"' . ($v === $selected ? ' selected' : '') . '>' . $this->e(ucwords(str_replace('_', ' ', $v))) . '</option>'; return $out; }
    protected function badge($value) { $class = $value === 'active' || $value === 'success' ? 'label-success' : ($value === 'draft' || $value === 'suspended' ? 'label-warning' : 'label-default'); return '<span class="label ' . $class . '">' . $this->e(ucwords(str_replace('_', ' ', $value))) . '</span>'; }
    protected function url($action, array $extra = []) { $url = $this->moduleLink . '&action=' . rawurlencode($action); foreach ($extra as $k => $v) $url .= '&' . rawurlencode($k) . '=' . rawurlencode($v); return $this->e($url); }
    protected function e($value) { return htmlspecialchars((string) ($value ?? ''), ENT_QUOTES, 'UTF-8'); }
}
