<?php
/**
 * Suite 02 — application catalog and manifest system.
 *
 * The catalog is a database, not code. This suite proves: every shipped manifest
 * parses and validates, the approval workflow refuses to publish an untested
 * version, the compatibility matrix drives what the wizard may offer, customers
 * only ever see published-and-deployable applications, the security validator
 * rejects a hostile manifest, and the wide registry imports as draft rows that
 * cannot be deployed.
 */

require_once __DIR__ . '/bootstrap.php';

use Ch247Apps\Catalog\ApplicationService;
use Ch247Apps\Catalog\CatalogImporter;
use Ch247Apps\Catalog\CategoryService;
use Ch247Apps\Catalog\Manifest;
use Ch247Apps\Catalog\ManifestRepository;
use Ch247Apps\Catalog\ManifestValidator;
use Ch247Apps\Catalog\VersionService;
use Ch247Apps\Core\Actor;
use Ch247Apps\Core\Audit;
use Ch247Apps\Core\AuthorizationException;
use Ch247Apps\Core\Clock;
use Ch247Apps\Core\Db;
use Ch247Apps\Core\NotFoundException;
use Ch247Apps\Core\Rbac;
use Ch247Apps\Core\StateException;
use Ch247Apps\Core\ValidationException;
use Ch247Apps\Core\Yaml;

Harness::boot();
Harness::relaxRateLimits();

$super = Harness::adminActor(1);
$customer = Harness::customerActor(42);
$manifestDir = dirname(__DIR__) . '/manifests';

/* ------------------------------------------------------- every manifest ---- */

section('Every shipped manifest parses, validates and is deployable-shaped');

$ids = ManifestRepository::availableIds();
T::ok('the manifest repository finds the shipped manifests', count($ids) >= 11);
foreach (['wordpress', 'n8n', 'nextcloud', 'uptime-kuma', 'vaultwarden', 'immich', 'grafana', 'gitea',
    'postgresql', 'redis', 'traefik'] as $expected) {
    T::ok('ships a manifest for ' . $expected, in_array($expected, $ids, true));
}

$validator = new ManifestValidator();
$invalid = [];
$manifests = [];
foreach ($ids as $id) {
    $manifest = ManifestRepository::load($id);
    if (!$manifest instanceof Manifest) {
        $invalid[] = $id . ': did not load';
        continue;
    }
    $manifests[$id] = $manifest;
    $result = $validator->validate($manifest);
    if (!$result['valid']) {
        foreach ($result['errors'] as $error) {
            $invalid[] = $id . ': ' . $error['field'] . ' — ' . $error['message'];
        }
    }
}
T::is('every shipped manifest passes structural and security validation', [], $invalid);

$n8n = $manifests['n8n'];
T::is('the manifest id is the catalog slug', 'n8n', $n8n->id());
T::is('kind is an application', Manifest::KIND_APPLICATION, $n8n->kind());
T::is('the engine is docker-compose', Manifest::ENGINE_DOCKER_COMPOSE, $n8n->engine());
T::is('the primary service is declared', 'app', $n8n->primaryService());
T::is('the primary port comes from the manifest', 5678, $n8n->primaryPort());
T::is('images are pinned, never :latest', 'n8nio/n8n:1.70.1', $n8n->service('app')['image']);
T::is('requirements are read in MB', 1024, $n8n->requirements()['memory_min_mb']);
T::is('storage units are normalised', 5120, $n8n->requirements()['storage_min_mb']);
T::ok('a required secret is generated by the platform', $n8n->environment()['generated']['N8N_ENCRYPTION_KEY']['secret']);
T::is('the health check path comes from the manifest', '/healthz', $n8n->healthcheck()['path']);
T::is('the health check interval is in seconds', 30, $n8n->healthcheck()['interval']);
T::is('backup retention comes from the manifest', 14, $n8n->backup()['retention_days']);
T::is('the update strategy is declarative', 'recreate', $n8n->update()['strategy']);
T::ok('update takes a backup first', $n8n->update()['backup_before']);
T::ok('update rolls back on failure', $n8n->update()['rollback_on_failure']);
T::is('dependencies resolve to catalog entries', 'postgresql', $n8n->dependencies()[0]['id']);
T::is('deep get() walks the document', 'postgresdb', $n8n->get('services.app.environment.DB_TYPE'));
T::is('get() returns a default for a missing path', 'fallback', $n8n->get('services.nope.image', 'fallback'));

section('Volumes declared inside a service are folded into the manifest volume list');

$immich = $manifests['immich'];
$volumeNames = [];
foreach ($immich->volumes() as $volume) {
    $volumeNames[] = $volume['name'];
}
sort($volumeNames);
T::is('multi-service volumes are collected once each',
    ['dbdata', 'mlcache', 'upload'], $volumeNames);
T::is('a shared volume keeps its size', 409600, $immich->volumes()['upload']['size_mb']);
T::ok('the media volume is excluded from backups by design', !$immich->volumes()['upload']['backup']);
T::is('four services plus a database make five', 5, count($immich->services()));
T::is('internal services are not published', true, $immich->services()['db']['internal']);

section('A manifest normalises deterministically and its hash is stable');

$hashA = $n8n->hash();
$reparsed = Manifest::fromYaml($n8n->toYaml());
T::is('normalising twice produces the same document', $hashA, $reparsed->hash());
T::is('the hash is a 64 character digest', 64, strlen($hashA));
$partial = Manifest::fromArray([
    'id' => 'Demo App',
    'name' => 'Demo App',
    'services' => ['app' => ['image' => 'vendor/demo:1.0', 'port' => 8080]],
]);
T::is('a slug is derived from the name when absent', 'demo-app', $partial->slug());
T::is('a missing engine defaults to docker-compose', Manifest::ENGINE_DOCKER_COMPOSE, $partial->engine());
T::is('a missing kind defaults to application', Manifest::KIND_APPLICATION, $partial->kind());
T::is('the schema version is stamped', Manifest::SCHEMA_VERSION, $partial->schemaVersion());
T::is('ports are derived from the services', [8080], $partial->ports());

/* ------------------------------------------------------------ validation ---- */

section('The security validator refuses hostile manifests');

function hostileManifest(array $overrides)
{
    $base = Yaml::parse(file_get_contents(dirname(__DIR__) . '/manifests/uptime-kuma.yaml'));
    foreach ($overrides as $path => $value) {
        $keys = explode('.', $path);
        $ref = &$base;
        foreach ($keys as $key) {
            if (!isset($ref[$key]) || !is_array($ref[$key])) {
                $ref[$key] = [];
            }
            $ref = &$ref[$key];
        }
        $ref = $value;
        unset($ref);
    }
    return Manifest::fromArray($base);
}

$validator = new ManifestValidator();

$privileged = $validator->validate(hostileManifest(['services.app.privileged' => true]));
T::ok('privileged containers are refused', !$privileged['valid']);
T::contains('and say why', 'privileged', strtolower(json_encode($privileged['errors'])));

$hostNetwork = $validator->validate(hostileManifest(['services.app.network_mode' => 'host']));
T::ok('host networking is refused', !$hostNetwork['valid']);

$socket = $validator->validate(hostileManifest([
    'services.app.volumes' => [['name' => 'sock', 'mount' => '/var/run/docker.sock', 'host_path' => '/var/run/docker.sock']],
]));
T::ok('a docker.sock bind mount is refused', !$socket['valid']);

$capabilities = $validator->validate(hostileManifest(['services.app.cap_add' => ['SYS_ADMIN']]));
T::ok('dangerous capabilities are refused', !$capabilities['valid']);

$lowPort = $validator->validate(hostileManifest(['services.app.port' => 80, 'ports' => [80]]));
T::ok('a privileged host port is refused', !$lowPort['valid']);

$unpinned = $validator->validate(hostileManifest(['services.app.image' => 'louislam/uptime-kuma:latest']));
T::ok('an unpinned :latest image is refused', !$unpinned['valid']);

$badRegistry = $validator->validate(hostileManifest(['services.app.image' => 'evil.example.com/up:1.0.0']));
T::ok('an image outside the registry allow-list is refused', !$badRegistry['valid']);

$secretDefault = $validator->validate(hostileManifest([
    'environment' => ['required' => [['key' => 'API_TOKEN', 'secret' => true, 'default' => 'hunter2']]],
]));
T::ok('a secret shipped with a default value is refused', !$secretDefault['valid']);

$generatedManifest = hostileManifest([
    'environment' => ['required' => [['key' => 'API_TOKEN', 'generate' => 'password', 'description' => 'Upstream key.']],
        'optional' => [['key' => 'TZ', 'default' => 'UTC']]],
]);
$generatedEnv = $generatedManifest->environment();
T::ok('a generated variable is never asked of the customer', !isset($generatedEnv['required']['API_TOKEN']));
T::ok('it moves into the generated set instead', isset($generatedEnv['generated']['API_TOKEN']));
T::ok('and is treated as a secret', $generatedEnv['generated']['API_TOKEN']['secret']);
T::ok('a plain optional stays a prompt', isset($generatedEnv['optional']['TZ']));
$secretWithDefault = $validator->validate(hostileManifest([
    'environment' => ['generated' => [['key' => 'DB_PASSWORD', 'generate' => 'password', 'default' => 'changeme']]],
]));
T::ok('a generated secret may not ship a default', !$secretWithDefault['valid']);

$weakTls = $validator->validate(hostileManifest(['ssl' => ['enabled' => true, 'force_https' => true, 'min_tls' => 'VersionTLS10']]));
T::ok('TLS 1.0 is refused', !$weakTls['valid']);

$relativeMount = $validator->validate(hostileManifest([
    'volumes' => [['name' => 'data', 'service' => 'app', 'mount' => 'data', 'size_mb' => 1024]],
]));
T::ok('a relative container mount path is refused', !$relativeMount['valid']);

$tinyVolume = $validator->validate(hostileManifest([
    'volumes' => [['name' => 'data', 'service' => 'app', 'mount' => '/app/data', 'size_mb' => 0]],
    'services.app.volumes' => [['name' => 'data', 'mount' => '/app/data', 'size_mb' => 0]],
]));
T::ok('a zero-size volume is refused', !$tinyVolume['valid']);

$remoteDriver = $validator->validate(hostileManifest([
    'volumes' => [['name' => 'data', 'service' => 'app', 'mount' => '/app/data', 'size_mb' => 1024, 'driver' => 'nfs']],
]));
T::ok('a remote volume driver is refused by default', !$remoteDriver['valid']);

$noHealth = hostileManifest(['healthcheck' => ['type' => 'http', 'path' => '/']]);
T::is('a health check without a port falls back to the primary service port',
    3001, $noHealth->healthcheck()['port']);
T::ok('and still validates', $validator->validate($noHealth)['valid']);
$noHealthAtAll = $validator->validate(hostileManifest(['healthcheck' => ['type' => 'none']]));
T::ok('refusing a health check is allowed but warned about, never silently ONLINE',
    count($noHealthAtAll['warnings']) > 0);

$badInterval = $validator->validate(hostileManifest([
    'healthcheck' => ['type' => 'http', 'path' => '/', 'port' => 3001, 'interval' => '1s', 'timeout' => '5s', 'retries' => 3],
]));
T::ok('a health check interval below the floor is refused', !$badInterval['valid']);

$timeoutAfterInterval = $validator->validate(hostileManifest([
    'healthcheck' => ['type' => 'http', 'path' => '/', 'port' => 3001, 'interval' => '10s', 'timeout' => '30s', 'retries' => 3],
]));
T::ok('a timeout longer than the interval is refused', !$timeoutAfterInterval['valid']);

$danglingDependency = $validator->validate(hostileManifest([
    'services' => ['app' => ['image' => 'louislam/uptime-kuma:2.0.0-beta.1', 'port' => 3001, 'primary' => true,
        'depends_on' => ['ghost']]],
]));
T::ok('a depends_on pointing at a missing service is refused', !$danglingDependency['valid']);

$rootWarning = $validator->validate(hostileManifest(['services.app.user' => '0:0']));
T::ok('running as root produces a warning, not a silent pass', count($rootWarning['warnings']) > 0);

$noId = $validator->validateYaml("name: No Id\nservices:\n  app:\n    image: vendor/x:1.0.0\n    port: 8080\n");
T::ok('a manifest without an id is refused', !$noId['valid']);

T::ok('a valid manifest reports no errors', $validator->validate($n8n)['errors'] === []);
$report = $validator->validate($n8n)['report'];
foreach (['identity', 'deployment', 'services', 'environment', 'volumes', 'healthcheck', 'security'] as $section) {
    T::ok('the validation report covers ' . $section, array_key_exists($section, $report));
}
T::is('the report snapshots the manifest hash it validated', $n8n->hash(), $report['manifest_hash']);

/* ------------------------------------------------------------- categories ---- */

section('Categories are a seeded taxonomy, extendable by administrators');

$categories = new CategoryService($super);
$seeded = $categories->seedTaxonomy();
T::ok('the taxonomy is seeded', $seeded > 0);
T::is('seeding again changes nothing', 0, $categories->seedTaxonomy());

$listing = $categories->listing();
T::ok('the listing covers the taxonomy', count($listing) >= 25);
$slugs = [];
foreach ($listing as $category) {
    $slugs[] = $category['slug'];
}
foreach (['ai', 'automation', 'cms', 'database', 'infrastructure', 'monitoring', 'security'] as $required) {
    T::ok('includes the ' . $required . ' category', in_array($required, $slugs, true));
}
T::ok('a category can be found by slug', $categories->find('automation') !== null);
T::is('an unknown category is null', null, $categories->find('not-a-category'));

$created = $categories->create(['name' => 'Quantum', 'slug' => 'quantum', 'description' => 'Quantum tooling']);
T::ok('an administrator can add a category', (int) $created['id'] > 0);
T::throws('a customer cannot', AuthorizationException::class, function () use ($customer) {
    (new CategoryService($customer))->create(['name' => 'Nope', 'slug' => 'nope']);
});
T::throws('a duplicate slug is refused', ValidationException::class, function () use ($categories) {
    $categories->create(['name' => 'Quantum Two', 'slug' => 'quantum']);
});

/* ---------------------------------------------------------------- import ---- */

section('The importer turns manifests into catalog rows without duplicating work');

$importer = new CatalogImporter($super);
$first = $importer->importFromDirectory($manifestDir, ['publish' => true]);
T::is('no manifest failed to import', [], $first['errors']);
T::ok('applications were created', $first['applications'] >= 11);
T::ok('versions were created', $first['versions'] >= 11);
T::ok('validated manifests were published', $first['published'] >= 11);
T::ok('the registry catalog was imported', $first['registry'] > 100);

$second = $importer->importFromDirectory($manifestDir, ['publish' => true]);
T::is('re-importing is idempotent (no new registry rows)', 0, $second['registry']);
T::is('and still reports no errors', [], $second['errors']);
T::is('one application row per manifest slug', 1, Db::count('applications', ['slug' => 'n8n']));

$wordpress = Db::first('applications', ['slug' => 'wordpress']);
T::is('wordpress is published', ApplicationService::STATUS_PUBLISHED, $wordpress['status']);
T::is('and deployable', 1, (int) $wordpress['deployable']);
T::is('requirements came from the manifest', 1024,
    (int) Db::first('application_versions', ['application_id' => (int) $wordpress['id']])['minimum_memory_mb']);
T::is('the manifest hash is stored with the version', 64,
    strlen((string) Db::first('application_versions', ['application_id' => (int) $wordpress['id']])['manifest_hash']));
T::is('the manifest snapshot is stored verbatim', 'wordpress',
    Yaml::parse(Db::first('application_versions', ['application_id' => (int) $wordpress['id']])['manifest'])['id']);

$postgres = Db::first('applications', ['slug' => 'postgresql']);
T::is('postgresql is catalogued as infrastructure', Manifest::KIND_INFRASTRUCTURE, $postgres['kind']);
$traefik = Db::first('applications', ['slug' => 'traefik']);
T::is('traefik is catalogued as infrastructure', Manifest::KIND_INFRASTRUCTURE, $traefik['kind']);
T::is('and needs admin approval', 1, (int) $traefik['requires_admin_approval']);
$lemp = Db::first('applications', ['slug' => 'lemp-stack']);
T::is('a stack is catalogued as a platform', Manifest::KIND_PLATFORM, $lemp['kind']);

section('Registry-only entries are catalog rows that cannot be deployed');

$ghost = Db::first('applications', ['slug' => 'ghost']);
T::ok('a registry entry exists in the catalog', $ghost !== null);
T::is('but is a draft', ApplicationService::STATUS_DRAFT, $ghost['status']);
T::is('and is explicitly not deployable', 0, (int) $ghost['deployable']);
T::is('with no version behind it', 0, Db::count('application_versions', ['application_id' => (int) $ghost['id']]));
T::contains('and carries an honest admin note', 'awaiting a validated manifest', (string) $ghost['admin_notes']);

$applications = new ApplicationService($super);
$denied = T::throws('a draft application cannot be installed', StateException::class, function () use ($applications, $ghost) {
    $applications->assertDeployable((int) $ghost['id'], 'vps');
});
T::is('with a machine-readable error code', 'APPLICATION_NOT_PUBLISHED', $denied->context()['error_code']);

$statistics = CatalogImporter::statistics();
T::ok('statistics count the catalog', $statistics['total'] > 100);
T::is('published entries are the deployable subset', $statistics['deployable'], $statistics['published']);
T::ok('drafts outnumber published entries', $statistics['draft'] > $statistics['published']);

/* -------------------------------------------------------- compatibility ---- */

section('The compatibility matrix decides which hosting types the wizard may offer');

T::is('wordpress supports the full hosting range',
    ['shared', 'cpanel', 'vps', 'dedicated', 'docker', 'kubernetes'],
    $applications->supportedHostingTypes((int) $wordpress['id']));
$n8nRow = Db::first('applications', ['slug' => 'n8n']);
T::is('n8n is not a shared-hosting product',
    ['vps', 'dedicated', 'docker', 'kubernetes'],
    $applications->supportedHostingTypes((int) $n8nRow['id']));

$kuma = Db::first('applications', ['slug' => 'uptime-kuma']);
$matrix = $applications->compatibility((int) $kuma['id']);
T::ok('every hosting type has an explicit entry', count($matrix) === count(Manifest::HOSTING_TYPES));
T::ok('cpanel is explicitly unsupported for a container app', !$matrix['cpanel']['supported']);
T::ok('vps is supported', $matrix['vps']['supported']);

$incompatible = T::throws('installing on an unsupported type is refused', StateException::class,
    function () use ($applications, $kuma) {
        $applications->assertDeployable((int) $kuma['id'], 'cpanel');
    });
T::is('with a compatibility error code', 'APPLICATION_INCOMPATIBLE_HOSTING', $incompatible->context()['error_code']);

$applications->setCompatibility((int) $kuma['id'], [
    'vps' => ['supported' => true, 'recommended' => true],
    'dedicated' => ['supported' => true],
    'cpanel' => ['supported' => false, 'notes' => 'Containers only'],
]);
T::is('an administrator can update the matrix', 'Containers only',
    $applications->compatibility((int) $kuma['id'])['cpanel']['notes']);

$dependencies = $applications->dependencies(Db::first('applications', ['slug' => 'nextcloud'])['id']);
T::is('nextcloud declares two catalog dependencies', 2, count($dependencies));
T::ok('and they are linked to real catalog rows', $dependencies[0]['application'] !== null);

/* -------------------------------------------------------------- workflow ---- */

section('The approval workflow refuses to publish untested versions');

$versions = new VersionService($super);
$draftApp = $applications->upsert([
    'name' => 'Bleeding Edge', 'slug' => 'bleeding-edge', 'category' => 'developer-tools',
    'kind' => Manifest::KIND_APPLICATION, 'summary' => 'A brand new entry.',
]);

$uploadedManifest = <<<'YAML'
schema: 1
id: bleeding-edge
name: Bleeding Edge
category: developer-tools
kind: application
summary: A brand new catalog entry used to prove the approval workflow.
description: This manifest is uploaded through the admin console rather than shipped with the platform, which is the path a new catalog entry always takes before it can be offered to customers.
website: https://example.test
license: MIT
version: 0.1.0
deployment:
  engine: docker-compose
  supported_hosting_types: [vps, dedicated, docker]
requirements:
  cpu_min: 1
  memory_min_mb: 512
  storage_min_mb: 1024
services:
  app:
    image: vendor/bleeding-edge:0.1.0
    port: 8080
    primary: true
    volumes:
      - name: data
        mount: /data
        size_mb: 1024
environment:
  required:
    - key: ADMIN_EMAIL
      description: Administrator address.
      validation: email
  generated:
    - key: APP_KEY
      generate: secret
      secret: true
volumes:
  - name: data
    service: app
    mount: /data
    size_mb: 1024
healthcheck:
  type: http
  path: /health
  port: 8080
domain:
  enabled: true
  required: true
ssl:
  enabled: true
backup:
  enabled: true
update:
  strategy: recreate
YAML;

$created = $versions->create([
    'application_id' => (int) $draftApp['id'],
    'version' => '0.1.0',
    'manifest' => $uploadedManifest,
]);
T::ok('a manifest upload creates a version', (int) $created['version']['id'] > 0);
T::ok('and it validates', $created['validation']['valid']);
T::is('the uploaded manifest is snapshotted with the version', 'bleeding-edge',
    Yaml::parse($created['version']['manifest'])['id']);
T::is('a version whose manifest id does not match the application is refused', 'uptime-kuma',
    (function () use ($versions, $draftApp) {
        try {
            $versions->create([
                'application_id' => (int) $draftApp['id'],
                'version' => '9.9.9',
                'manifest' => file_get_contents(dirname(__DIR__) . '/manifests/uptime-kuma.yaml'),
            ]);
        } catch (ValidationException $e) {
            return 'uptime-kuma';
        }
        return 'accepted';
    })());

$report = json_decode((string) $created['version']['validation_report'], true);
T::ok('the manifest gate passed automatically', $report['manifest']['passed']);
T::ok('the security gate passed automatically', $report['security']['passed']);
foreach (['deployment', 'health_check', 'backup', 'update', 'uninstall'] as $gate) {
    T::ok('the ' . $gate . ' gate starts unproven', !$report[$gate]['passed']);
}

$blocked = T::throws('publishing an untested version is refused', StateException::class,
    function () use ($versions, $created) {
        $versions->publish((int) $created['version']['id']);
    });
T::is('and lists exactly which gates are missing',
    ['deployment', 'health_check', 'backup', 'update', 'uninstall'], $blocked->context()['missing']);
T::throws('and the application cannot be published either', StateException::class,
    function () use ($applications, $draftApp) {
        $applications->publish((int) $draftApp['id']);
    });

foreach (['deployment', 'health_check', 'backup', 'update', 'uninstall'] as $gate) {
    $versions->recordGate((int) $created['version']['id'], $gate, true, ['deployment_id' => 900 + crc32($gate) % 100]);
}
$publishedVersion = $versions->publish((int) $created['version']['id']);
T::is('the version publishes once every gate has passed', 'published', $publishedVersion['status']);
T::ok('and is flagged latest', (bool) $publishedVersion['is_latest']);

$applications->transition((int) $draftApp['id'], ApplicationService::STATUS_VALIDATING);
$applications->transition((int) $draftApp['id'], ApplicationService::STATUS_TESTING);
$applications->transition((int) $draftApp['id'], ApplicationService::STATUS_APPROVED);
$publishedApp = $applications->transition((int) $draftApp['id'], ApplicationService::STATUS_PUBLISHED);
T::is('the application walks the full workflow', ApplicationService::STATUS_PUBLISHED, $publishedApp['status']);
T::is('and becomes deployable', 1, (int) $publishedApp['deployable']);
T::throws('skipping a stage is refused', StateException::class, function () use ($applications, $kuma) {
    $applications->transition((int) $kuma['id'], ApplicationService::STATUS_TESTING);
});

section('Publishing, suspending and deprecating are permission-checked and audited');

T::throws('a customer cannot publish', AuthorizationException::class, function () use ($customer, $kuma) {
    (new ApplicationService($customer))->publish((int) $kuma['id']);
});
T::throws('a customer cannot create catalog entries', AuthorizationException::class, function () use ($customer) {
    (new ApplicationService($customer))->upsert(['name' => 'Sneaky', 'slug' => 'sneaky']);
});
$staff = Harness::staffActor(2);
T::throws('staff cannot publish either', AuthorizationException::class, function () use ($staff, $kuma) {
    (new ApplicationService($staff))->publish((int) $kuma['id']);
});

$suspended = $applications->transition((int) $draftApp['id'], ApplicationService::STATUS_SUSPENDED,
    ['reason' => 'Upstream licence change']);
T::is('suspension is recorded', ApplicationService::STATUS_SUSPENDED, $suspended['status']);
T::is('with the reason', 'Upstream licence change', $suspended['suspension_reason']);
T::is('and stops new installs', 0, (int) $suspended['deployable']);
T::throws('a suspended application cannot be installed', StateException::class,
    function () use ($applications, $draftApp) {
        $applications->assertDeployable((int) $draftApp['id'], 'vps');
    });

$auditRows = Audit::search(['action' => Audit::APPLICATION_SUSPENDED]);
T::ok('the suspension was audited', count($auditRows) >= 1);
T::is('and the audit row names the resource', 'application', Audit::present($auditRows[0])['resource_type']);
T::ok('the chain still verifies after all that writing', Audit::verifyChain()['valid']);

$deprecated = $versions->deprecate((int) $created['version']['id'], 'Superseded by 0.2.0');
T::is('a version can be deprecated', VersionService::STATUS_DEPRECATED, $deprecated['status']);
T::ok('and is no longer the latest', !(bool) $deprecated['is_latest']);

/* ----------------------------------------------------------- marketplace ---- */

section('The marketplace only ever shows published, deployable applications');

$customerCatalog = new ApplicationService($customer);
$page = $customerCatalog->query(['limit' => 200]);
$slugs = [];
foreach ($page['items'] as $item) {
    $slugs[] = $item['slug'];
    if ($item['status'] !== ApplicationService::STATUS_PUBLISHED || !$item['deployable']) {
        $slugs[] = 'LEAK:' . $item['slug'];
    }
}
T::ok('a customer sees the deployable catalog', in_array('n8n', $slugs, true));
T::ok('including infrastructure entries', in_array('postgresql', $slugs, true));
$leaks = array_values(array_filter($slugs, function ($slug) {
    return strpos($slug, 'LEAK:') === 0;
}));
T::is('no draft, suspended or registry-only entry leaks to customers', [], $leaks);
T::ok('registry-only entries stay invisible', !in_array('ghost', $slugs, true));

$adminPage = (new ApplicationService($super))->query(['limit' => 500]);
T::ok('an administrator sees the whole catalog', $adminPage['total'] > $page['total']);
T::ok('including drafts', in_array('ghost', array_map(function ($item) {
    return $item['slug'];
}, $adminPage['items']), true));

$search = $customerCatalog->query(['q' => 'workflow automation']);
T::ok('full-text search finds n8n', in_array('n8n', array_map(function ($item) {
    return $item['slug'];
}, $search['items']), true));

$byCategory = $customerCatalog->query(['category' => 'monitoring', 'limit' => 50]);
$categorySlugs = array_map(function ($item) {
    return $item['slug'];
}, $byCategory['items']);
T::ok('category filtering works', in_array('uptime-kuma', $categorySlugs, true));
T::ok('and grafana is in monitoring too', in_array('grafana', $categorySlugs, true));
T::ok('but n8n is not', !in_array('n8n', $categorySlugs, true));

$infrastructure = $customerCatalog->query(['kind' => Manifest::KIND_INFRASTRUCTURE, 'limit' => 50]);
T::ok('kind filtering separates infrastructure from applications', count($infrastructure['items']) >= 2);
foreach ($infrastructure['items'] as $item) {
    T::is('every result of a kind filter has that kind', Manifest::KIND_INFRASTRUCTURE, $item['kind']);
}

$featured = $customerCatalog->query(['featured' => true, 'limit' => 50]);
T::ok('featured filtering works', count($featured['items']) >= 3);

$paged = $customerCatalog->query(['limit' => 3, 'page' => 2]);
T::is('pagination respects the limit', 3, count($paged['items']));
T::is('and reports the page', 2, $paged['page']);
T::ok('and reports the page count', $paged['pages'] > 1);

$byName = $customerCatalog->query(['sort' => 'name', 'limit' => 5]);
$names = array_map(function ($item) {
    return $item['name'];
}, $byName['items']);
$sorted = $names;
sort($sorted);
T::is('name sorting is alphabetical', $sorted, $names);

section('Application detail exposes requirements, versions and plans');

$detail = $customerCatalog->detail('n8n');
T::is('detail resolves by slug', 'n8n', $detail['slug']);
T::ok('the long description is included', strlen((string) $detail['description']) > 20);
T::ok('at least one published version is listed', count($detail['versions']) >= 1);
T::is('the current version is the published one', '1.70.1', $detail['current_version']);
T::is('requirements are shown to the customer before purchase', 1024, $detail['requirements']['memory_min_mb']);
T::is('the category is included', 'automation', $detail['category']['slug']);
T::is('admin-only notes are not exposed to customers', null, $detail['admin_notes']);
T::ok('the hosting matrix is included', isset($detail['hosting_types']['vps']));
T::ok('dependencies are included', count($detail['dependencies']) >= 1);

T::throws('a customer cannot open a draft application', NotFoundException::class,
    function () use ($customerCatalog) {
        $customerCatalog->detail('ghost');
    });
$adminDetail = (new ApplicationService($super))->detail('ghost');
T::is('an administrator can', 'ghost', $adminDetail['slug']);
T::contains('and sees why it is not deployable', 'awaiting a validated manifest', (string) $adminDetail['admin_notes']);

T::throws('an unknown slug is a 404', NotFoundException::class, function () use ($customerCatalog) {
    $customerCatalog->detail('does-not-exist');
});

/* --------------------------------------------------------- version replay ---- */

section('A deployment always builds from the approved manifest snapshot');

$n8nVersion = Db::first('application_versions', [
    'application_id' => (int) Db::first('applications', ['slug' => 'n8n'])['id'], 'status' => 'published',
]);
$rebuilt = ManifestRepository::forVersion((int) $n8nVersion['id']);
T::is('the snapshot rebuilds to the same manifest', $n8nVersion['manifest_hash'], $rebuilt->hash());
T::is('and the same primary image', 'n8nio/n8n:1.70.1', $rebuilt->service('app')['image']);

Db::update('application_versions', ['manifest_hash' => str_repeat('a', 64)], ['id' => (int) $n8nVersion['id']]);
T::throws('an edited snapshot that no longer matches its hash is refused', StateException::class,
    function () use ($n8nVersion) {
        ManifestRepository::forVersion((int) $n8nVersion['id']);
    });
Db::update('application_versions', ['manifest_hash' => $n8nVersion['manifest_hash']], ['id' => (int) $n8nVersion['id']]);
T::is('restoring the hash makes it loadable again', $n8nVersion['manifest_hash'],
    ManifestRepository::forVersion((int) $n8nVersion['id'])->hash());

$bySlug = ManifestRepository::forApplication('wordpress');
T::is('forApplication resolves the published version', 'wordpress', $bySlug->id());
T::throws('forApplication refuses an unknown slug', NotFoundException::class, function () {
    ManifestRepository::forApplication('not-a-real-app');
});

$uploaded = ManifestRepository::fromYaml(file_get_contents($manifestDir . '/redis.yaml'));
T::is('an uploaded manifest is parsed the same way', 'redis', $uploaded->id());
T::throws('an oversized upload is refused', ValidationException::class, function () {
    ManifestRepository::fromYaml("id: big\nname: Big\npadding: '" . str_repeat('x', 300000) . "'\n");
});

$applications->recordInstall(Db::first('applications', ['slug' => 'n8n'])['id']);
T::is('install counts drive the popular sort', 1,
    (int) Db::first('applications', ['slug' => 'n8n'])['install_count']);

Harness::shutdown();
exit(T::summary());
