<?php
//
///*
// * Using Cron Manager. Do not edit this file.
// * Add your hooks in /app/hooks/ directory.
// */
//
$exploded = explode(DIRECTORY_SEPARATOR, $_SERVER['SCRIPT_NAME']);
$script = end($exploded);

if($script === 'pop.php' || $script === 'pipe.php'|| $script === "viewinvoice.php")
{
    return;
}

require_once __DIR__ . DIRECTORY_SEPARATOR . 'Core' . DIRECTORY_SEPARATOR . 'Bootstrap.php';
\ModulesGarden\ProductsReseller\Server\Smtphosting\Core\Hook\HookManager::create(__DIR__);
